services:
  backend:
    build: .
    container_name: hamperapp-backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - valkey
    restart: unless-stopped




  valkey:
    image: valkey/valkey:8-alpine
    container_name: hamperapp-valkey
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - valkey-data:/data
    command: valkey-server --appendonly yes

volumes:
  valkey-data: